apiVersion: v1
kind: Namespace
metadata:
  name: ate-demo-pi
---
apiVersion: ate.dev/v1alpha1
kind: WorkerPool
metadata:
  name: pi-durable
  namespace: ate-demo-pi
  labels:
    workload: pi-durable
spec:
  replicas: 2
  workerImage: localhost:5001/ateom-gvisor:latest
  template:
    nodeSelector:
      ate.dev/substrate-version: "SUBSTRATE_VERSION"
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi
